Feature/address find
FRONTENDBOOTCAMP-12th/TailWind-MarketCarly pull request #168
Opened 2024-12-27 08:29 UTC by betteree

## PR 유형

-   [x] 새로운 기능 추가
-   [x] 버그 수정
-   [] CSS 등 사용자 UI 디자인 변경
-   [] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
-   [] 코드 리팩토링
-   [] 주석 추가 및 수정
-   [] 문서 수정
-   [] 테스트 추가, 테스트 리팩토링
-   [] 빌드 부분 혹은 패키지 매니저 수정
-   [] 파일 혹은 폴더명 수정
-   [] 파일 혹은 폴더 삭제

## PR 체크리스트

-   [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.
-   [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

### PR 상세

- 주소찾기 기능 구현
- 이메일 확인 란ture로 넘겨주기

## 이슈

resolves #161

2024-12-28 11:02 UTC, Littlestar0508 approved these changes
코드 확인했습니다!

2024-12-30 00:01 UTC, workerKwon requested changes

2024-12-30 00:01 UTC, workerKwon commented on src/pages/Register/Register.js
> +                            <c-button @click="${this.handleFindAddr}">주소 찾기</c-button>
@click="${handleFindAddr(this.inputs)}" 로 해도 될거 같은데 한번 해보시겠어요? 된다면 위에 handleFindAddr() {} 함수는 지워도 될거에요.

2024-12-30 00:32 UTC, jimyeong21 approved these changes
나은님 짱👍

2024-12-30 00:51 UTC, workerKwon approved these changes

2024-12-30 00:54 UTC, merged