feat : 팝업창 및 사이드바 개발
FRONTENDBOOTCAMP-12th/TailWind-MarketCarly pull request #31
Opened 2024-12-12 00:43 UTC by lyb9030

## PR 유형

-   [x] 새로운 기능 추가
-   [] 버그 수정
-   [] CSS 등 사용자 UI 디자인 변경
-   [] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
-   [] 코드 리팩토링
-   [] 주석 추가 및 수정
-   [] 문서 수정
-   [] 테스트 추가, 테스트 리팩토링
-   [] 빌드 부분 혹은 패키지 매니저 수정
-   [] 파일 혹은 폴더명 수정
-   [] 파일 혹은 폴더 삭제

## PR 체크리스트

-   [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.
-   [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

### PR 상세

- 홈페이지 우측 사이드바 제작
- 홈페이지 안내 문구 팝업 제작

## 이슈

resolves #17

2024-12-12 01:06 UTC, workerKwon requested changes

2024-12-12 01:16 UTC, betteree commented on src/pages/popup/popup.js
> +                <div class="popupText">
저희 클래스명을 popup-text  요런식으로 구분해야 할 단어들 사이에 - 를 넣기로 정했어서 카멜케이스 방식말고 요렇게 바꿔주시면 좋을거같습니다!!

2024-12-12 01:16 UTC, betteree commented on src/pages/sidbar/sidbar.js
> +import reset from '/src/styles/reset.js';
src 를 @로 지정?이 되어있어서 src를 이렇게 쓰셨더라구요
import reset from '@/styles/reset.js'; 
이렇게 통일하면 좋을 거 같습니다!

2024-12-12 02:22 UTC, jimyeong21 commented
다른분들이 수정사항 잘 써주셔서 저는 딱히 코멘트 달 것이 없어보입니당 ㅎㅎ 
고생많으셨습니다 영범님!

2024-12-12 04:21 UTC, jimyeong21 approved these changes

2024-12-12 04:36 UTC, workerKwon requested changes

2024-12-12 04:36 UTC, workerKwon commented on src/styles/popup.css
css 파일을 이렇게 만드시는것보다는
components/popup 폴더 안에 popupStyle.js 파일을 만드셔서 lit스타일 방식으로 추가하시는게 좋아보여요~

다른 팀원분들꺼 참고해서 적용하시면 쉬울거에요 ㅋㅋ
1. ![image](https://github.com/user-attachments/assets/76a7128d-f131-4894-a724-5fb853773dcf)
------------------------------
2. ![image](https://github.com/user-attachments/assets/2fea8aa9-bd22-467d-9d65-0069c0cba33a)

이 방법으로 해보시겠어요~?

2024-12-12 23:52 UTC, workerKwon approved these changes

2024-12-13 01:01 UTC, jimyeong21 approved these changes

2024-12-13 07:19 UTC, Littlestar0508 approved these changes
코드 확인했습니다

2024-12-13 07:19 UTC, betteree approved these changes

2024-12-13 07:20 UTC, merged