Feat: 생년월일 입력 컴포넌트
FRONTENDBOOTCAMP-12th/TailWind-MarketCarly pull request #85
Opened 2024-12-17 04:25 UTC by betteree

## PR 유형

-   [x] 새로운 기능 추가
-   [] 버그 수정
-   [] CSS 등 사용자 UI 디자인 변경
-   [] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
-   [] 코드 리팩토링
-   [] 주석 추가 및 수정
-   [] 문서 수정
-   [] 테스트 추가, 테스트 리팩토링
-   [] 빌드 부분 혹은 패키지 매니저 수정
-   [] 파일 혹은 폴더명 수정
-   [] 파일 혹은 폴더 삭제

## PR 체크리스트

-   [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.
-   [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

### PR 상세
- 숫자만 입력되도록 함
- 4/2/2 글자를 넘기지 않도록함

## 이슈

resolves #82

2024-12-17 04:44 UTC, Littlestar0508 approved these changes
코드 확인했습니다!
혹시 webkit을 사용하신 이유가 어떤건지 여쭤봐도 될까요??

2024-12-17 04:58 UTC, betteree commented
아 저게 number 타입 input에서 화살표 모양 없앨려고 한건데 Chrome, Safari, Edge, Opera 은 -webkit을 써야한다고해서 썼습니다!! firefox는 따로 처리해줘야하는데 당장은 firefox로 쓸 일이 없어서 그건 제외 했습니다!

2024-12-17 05:02 UTC, jimyeong21 approved these changes

2024-12-18 00:37 UTC, workerKwon requested changes

2024-12-18 00:37 UTC, workerKwon commented on src/components/birth/birth.js
> +    }
얘들은 어디에서 사용되는건가요?

2024-12-18 00:37 UTC, workerKwon commented on src/components/birth/birth.js
> +                padding: 0.5625rem 1.25rem;
일관성있게 스타일 파일에 옮겨주세용

2024-12-18 14:13 UTC, workerKwon approved these changes

2024-12-18 14:14 UTC, merged